output_path = "/scratch/ksidorov/gourd-experiments/lifting/unl/output"
metrics_path = "/scratch/ksidorov/gourd-experiments/lifting/unl/metrics"
experiments_folder = "/scratch/ksidorov/gourd-experiments/lifting/unl/synthetic"

[input.rcpsp-max]
arguments = [
    "max",
    "path|/home/ksidorov/disjoint-data/nontrivial/rcpsp-max/**/*.dzn"
    # "path|/home/ksidorov/disjoint-data/nontrivial/rcpsp-max/sm_j30_converted/PSP64.dzn"
]

[input.rcpsp]
arguments = [
    "std",
    "path|/home/ksidorov/disjoint-data/nontrivial/rcpsp/**/*.dzn"
    # "path|/home/ksidorov/disjoint-data/nontrivial/rcpsp/data_pack_d/pack003.dzn"
]

[program.pumpkin-lb]
binary = "/home/ksidorov/cumulative-lifting/main.py"
arguments = [
    "-n", "5", "-p", "100", "-b", "1",
    "--solver", "pumpkin",
    "--solver-flags", "-f --optimisation-strategy linear-unsat-sat",
    "-t", "3600000"
    # "-t", "60000"
]

[program.unl]
binary = "/home/ksidorov/Pumpkin-disjointness/target/release/examples/rcpsp"
arguments = [
    "-ln",
    "-t", "3600"
    # "-t", "60"
]

[slurm]
experiment_name = "unl"
output_folder = "./slurmout/"
partition = "compute-p2"
account = "research-eemcs-st"

[resource_limits]
time_limit = "1h 5m"
cpus = 1
mem_per_cpu = 4000
